### ISSUE TITLE
Make install-nls complains about @mkdir_p@: not found

### ISSUE THREAD

**Issue by elboulangero** [notroj/cadaver#16]
I added it to the CI: https://github.com/elboulangero/cadaver/commit/a30b79e92e9633bcccc8d951b93ad75b05405e79

The failure on Ubuntu 18 and Ubuntu 20 is due to a mismatch in gettext version, that's why I added Ubuntu 22 to the CI.

The error can be seen at https://github.com/elboulangero/cadaver/actions/runs/3358682685/jobs/5565952239

```
make[2]: Leaving directory '/home/runner/work/cadaver/cadaver/po'
touch ./stamp-po
/bin/sh: 6: @mkdir_p@: not found
/usr/bin/install: cannot create regular file '/usr/local/share/locale/es/LC_MESSAGES/cadaver.mo': No such file or directory
installing es.gmo as /usr/local/share/locale/es/LC_MESSAGES/cadaver.mo
/bin/sh: 6: @mkdir_p@: not found
/usr/bin/install: cannot create regular file '/usr/local/share/locale/en@quot/LC_MESSAGES/cadaver.mo': No such file or directory
```

Apparently the variable `@mkdir_p@` is not substituted, for some reason. It's been reported at https://savannah.gnu.org/bugs/?60201 by a Gentoo developer, but it's not clear what's the cause, or what the right fix is.

**Comment by notroj** [comment]
Thanks for reporting this. Not quite sure why it wasn't obviously failing but seems to be working with mkdir_p defined now:

https://github.com/notroj/cadaver/actions/runs/10101300065/job/27934571131?pr=48#step:8:16
