### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by Offerel** [notroj/cadaver#21]
I would like to use cadaver to sync specific files via WebDAV. But at least for me, it is really complicated to understand how this works.

For example i try to understand propget to compare the timestamp of a local file with the same on remote, but i have no idea, how to get the right timestamp only. Currently i use a bash script and curl to do that. But Curl will not download the file. My current bash script looks like:

```bash
#!/bin/bash
remote_file="https://my.url.com/files/user@myurl.com/file.name"
local_file="/home/user/Documents/file.name"
creds='user':'pass'

modified=$(curl --silent --basic --user $creds --head $remote_file | \
             awk '/^Last-Modified/{print $0}' | \
             sed 's/^Last-Modified: //')
remote_ctime=$(date --date="$modified" +%s)
local_ctime=$(stat -c %z "$local_file")
local_ctime=$(date --date="$local_ctime" +%s)

if [ $local_ctime -lt $remote_ctime ]; then
#	curl --silent --basic --user $creds $remote_file --output $local_file
	cadaver < getdb >/dev/null 2>&1
elif [ $remote_ctime -lt $local_ctime ]; then
#	curl  --basic --user $creds --silent -T $local_file $remote_file
	cadaver < putdb >/dev/null 2>&1
fi
```
There must be a easier way, using only cadaver and without curl. 
BTW: The commented line with curl, to download the file fails, username or password is incorrect for some reason. But the same credentials works with other commands. 

Would be nice to have a little bit more documentation.

**Comment by notroj** [comment]
Hi, please use the issues for reporting specific, reproducible bugs. It will always be true that more docs will be nice!

cadaver is not really designed or ideal to be used from scripts. sitecopy is designed to sync files over WebDAV. You should be able to do the same kind of thing with curl easily if this is just PUT/GET but I'm not a curl expert.
