### ISSUE TITLE
open WARNING: Untrusted server certificate presented for 

### ISSUE THREAD

**Issue by artlog** [notroj/cadaver#24]
**Describe the bug**

Using cadaver to access my personal nextcloud instance, i have to accept the certificate while it should be accepted.
so i did test on https://nextcloud.com provider and hit same issue.

It looks like system certificate autorities are not used.

**Environment**
 - cadaver --version
cadaver 0.23.3
neon 0.31.2: Library build, IPv6, libxml 2.9.10, zlib 1.2.11, GNU TLS 3.6.14.
readline 8.1
 - OS: debian 11.6
 - SSL library version: ldd /usr/bin/cadaver | grep tls
	libneon-gnutls.so.27 => /usr/lib/x86_64-linux-gnu/libneon-gnutls.so.27 (0x00007fba3d215000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fba3d015000)

**To Reproduce**

```
cadaver
dav:!> open https://nextcloud.com/
WARNING: Untrusted server certificate presented for `nextcloud.com':
Do you wish to accept the certificate? (y/n) y
```

**Debugging output**
For protocol issues please include neon debugging output which can be
enabled by running "set debug http" or similar in cadaver.

```
dav:/? set debug http
dav:/? open https://nextcloud.com/
HTTP session to https://nextcloud.com:443 begins.
Running pre_send hooks
Sending request headers:
OPTIONS / HTTP/1.1
User-Agent: cadaver/0.23.3 neon/0.31.2
Keep-Alive: 
Connection: TE, Keep-Alive
TE: trailers
Host: nextcloud.com

Sending request-line and headers:
Doing DNS lookup on nextcloud.com...
req: Connecting to 2a01:4f9:2b:29dc::155:443
WARNING: Untrusted server certificate presented for `nextcloud.com':
Issued to: nextcloud.com
Issued by: Let's Encrypt, US
Certificate is valid from Mon, 19 Dec 2022 04:00:23 GMT to Sun, 19 Mar 2023 04:00:22 GMT
Do you wish to accept the certificate? (y/n) 
```

certificate chain is indeed well accepted by certtool :
```
certtool --verify --infile nextcloud-com-chain.pem --verify-profile high
Loaded system trust (127 CAs available)
	Subject: CN=R3,O=Let's Encrypt,C=US
	Issuer: CN=ISRG Root X1,O=Internet Security Research Group,C=US
	Checked against: CN=ISRG Root X1,O=Internet Security Research Group,C=US
	Signature algorithm: RSA-SHA256
	Output: Verified. The certificate is trusted. 

	Subject: CN=nextcloud.com
	Issuer: CN=R3,O=Let's Encrypt,C=US
	Checked against: CN=R3,O=Let's Encrypt,C=US
	Signature algorithm: RSA-SHA256
	Output: Verified. The certificate is trusted. 

Chain verification output: Verified. The certificate is trusted. 
```

**Comment by notroj** [comment]
This likely a problem with the way neon was built. With GnuTLS neon has to be configured to use an appropriate system CA bundle or for neon 0.32.4 this should work automatically. Please try cadaver 0.24/neon 0.32.4 and reopen if you still see the problem.

**Comment by artlog** [comment]
thanks for reply, i opened this on my spare time, so i will see later within this week.

**Comment by artlog** [comment]
well i did recompile neon & cadaver with latest code, but this is irrelevant since neon did build openssl version, i am running out of time for this, this is more a debian packaging problem.

**Comment by artlog** [comment]
i did find origin of my problem, which is fully related to gnutls and unrelated to neon build or cadaver.
problem is on debian that provides a DST_Root_CA_X3.pem which is expired. Removing this ca from my system did it.
curiously it does not affect certtool but libraries using load ca.
