### ISSUE TITLE
manpage typo

### ISSUE THREAD

**Issue by macrohumanity** [notroj/cadaver#26]
I found a typo in the output of `man cadaver` and I would like to fix the issue.
this will be one of my first-ever legit pull requests so my apologies for the noobness!
after cloning via git, I searched for the manpage in the master branch for some time but could only find some hints in `./cadaver.spec.in` and `src/cadaver.c`. 
it is worth noting that I am not familiar with C, only bash, which could be the reason the trouble.
please tell me the manpage location and i will continue forward :)

**Comment by notroj** [comment]
Hi @macrohumanity - the man page is at doc/cadaver.1 - https://github.com/notroj/cadaver/blob/master/doc/cadaver.1

**Comment by notroj** [comment]
Thanks for the contribution. Merged via #27

FYI, if you use a comment like "closes #26" in your commit message, then Github will automatically close the issue when the PR is merged.

**Comment by macrohumanity** [comment]
that is a great tip - thank you! 
and thank you for closing this issue.
