### ISSUE TITLE
version scheme

### ISSUE THREAD

**Issue by chenrui333** [notroj/cadaver#31]
👋 it looks like `0.31.0-rc1` and `0.31.0` are not consistent with the other git tags, can you help deleting them to avoid confusion? Thanks!

![image](https://github.com/notroj/cadaver/assets/1580956/3db7627e-af09-4eb8-aea8-fd0a3deaa4e7)

relates to https://github.com/Homebrew/homebrew-core/pull/134790

**Comment by notroj** [comment]
Done, thanks for the report. Those tags probably came with the neon sources I imported via a subtree merge.
