### ISSUE TITLE
URLs with pathnames cause parse error

### ISSUE THREAD

**Issue by hugeblank** [notroj/cadaver#33]
**Describe the bug**
I have a webdav server hosted on `localhost:4200`. When I move the connection point to `/webdav` cadaver emits the following error:
![image](https://github.com/notroj/cadaver/assets/16393543/b9f9f71d-6d33-4be3-8731-6d8e4858138a)
Trying without the port number (`localhost/webdav`) still does not work, however trying with no path (`localhost:4200`) works. 

**Environment**
 - cadaver version: 0.24
 - neon version: 0.32.5
 - OS: Arch
 - SSL library version: 3.1.2-1

**To Reproduce**
`cadaver localhost:4200/webdav` (no server needed)

**Comment by notroj** [comment]
That's not a URL, it needs http:// or https:// at the beginning and then it will be accepted. Cadaver does parse some psuedo-URLs which is probably a mistake since they are ambiguous.

**Comment by hugeblank** [comment]
Yep that was the issue, dang! 

The readme could probably benefit with some clarification on what pseudo-urls do and don't work, or perhaps just drop them altogether.
