### ISSUE TITLE
Verbose mode for debugging

### ISSUE THREAD

**Issue by strugee** [notroj/cadaver#34]
(Skipping the bug report template since this is a feature request.)

It would be really nice if Cadaver had an option to dump the bodies of the requests it's making to the server. I'm trying to wrangle a Nextcloud shell script, but I can't get search to work properly - it keeps returning `501 Not Implemented`. This is frustrating because I don't have (easy) access to the server logs to see the request body, so without `--verbose` or something like it I have no way of knowing whether the requests Cadaver is sending are anywhere near what's in the Nextcloud WebDAV documentation.

**Comment by notroj** [comment]
Is `set debug http` not sufficient?

**Comment by strugee** [comment]
Oh, so sorry, I didn't know about that option - where is it documented?
