### ISSUE TITLE
complains about certificate

### ISSUE THREAD

**Issue by AdamRGrey** [notroj/cadaver#38]
**Describe the bug**
my SSL certificate is valid, i promise. But when I try to access my server, every time, I have to tell it to accept the certificate. (today is 2024-01-30, notably within the timeframe)

**Environment**
- cadaver 0.23.3
- neon 0.31.2: Library build, IPv6, libxml 2.9.10, zlib 1.2.11, GNU TLS 3.6.14.
- readline 8.1
 - OS: Debian 11
 - SSL library version:OpenSSL 1.1.1w-0+deb11u1 amd64

**To Reproduce**

1. have a server with a let's encrypt certificate
2. have nextcloud on it
3. `cadaver -t https://[DOMAIN]/nextcloud/remote.php/dav/files/[USER]/`

output:
```
WARNING: Untrusted server certificate presented for `[DOMAIN]':
Issued to: [DOMAIN]
Issued by: Let's Encrypt, US
Certificate is valid from Mon, 01 Jan 2024 01:01:28 GMT to Sun, 31 Mar 2024 01:01:27 GMT
Do you wish to accept the certificate? 
```

**Debugging output**
have to do this after connection, right?

**note also**
neither curl nor wget  complain, so I'm quite confident my system should trust the certificate

**Comment by notroj** [comment]
Did you build the binaries from source, if so how did you build them? `neon` has to be configured to use the correct system CA if you build with GnuTLS and neon 0.31.
